sudo: required
dist: trusty
language: clojure
script: lein doo chrome "tests" once
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "echo 'Installing Ganache'"
  - npm install -g ganache-cli
  - "echo 'Running Ganache'"
  - ganache-cli -p 8549 -b 1 --noVMErrorsOnRPCResponse > /dev/null &
