language: clojure
script: lein doo node "tests" once
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
  email: false
before_install:
- sudo add-apt-repository --yes ppa:ethereum/ethereum
- sudo apt-get -qq update
before_script:
- echo 'Installing Solc'
- sudo wget --no-check-certificate -P /bin https://github.com/ethereum/solidity/releases/download/v0.4.24/solc-static-linux
- sudo chmod a+x /bin/solc-static-linux
- sudo ln -s /bin/solc-static-linux /usr/bin/solc
- echo 'Compiling contracts'
- lein solc once
- echo 'Installing Ganache'
- npm install -g ganache-cli
- echo 'Running Ganache'
- ganache-cli -p 8549 -l 8000000 -d -m district0x > /dev/null &
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote rm origin
- git remote add origin https://${GH_TOKEN}@github.com/district0x/district-server-web3-events.git
  > /dev/null 2>&1
env:
  global:
  - secure: dvgKem385NivbhcCVOtS6u70lju12udL7EqB0WHlJqzAnTO2eJKKG/nQA71ABrggB0OAb+mk1XcA0h4tJV46IcxDa4ROvdN36DP+kvTwpgmXlo1PGf6XXffhI+d2khHksUUnZ3R/Ol732SiwoniWMCBZSw2raaH32l4GpLSJ+rhKYG3DdMRtmQsCLexykmuifHJ+29uh5z39zrmg1gsOGX/6zkKh2/SNKhx2Ns3X8teuGt4oJWvTD9xLS2RINGup+IOM+l4kXGt/Sby7g5r4XhmDpKsl8ybkulmNDbJ9EtR13LPsPdYxi2zDi4A1co9M/oGUEjjLf2s/cy40lFsbzutP39xNiOjdR9c5cH3b/oGTJ2mWW2kd2QplGfD2J6H/bsGChtesPqvtwaCWYegFwZCrhxTbCWEF/mnrzUaYSETGU0SQGO/8BprmrZjHNZHGQCDTU3Y6m4RhDYBSqX+KVl5AI/V6plOezAsdqpnf1iHT0ZcqD6MOPsocqc4negXvZhBSfDhY8JNkgMqddniNSWCXITtCvG+CdFp3YQpZoe2Vy2ZZ7qm+1oZSA3ebz8W8X6Y4KmmBzQGH8bsHJuIXgGhMItEpjoXwBVhBo535xg8eB61EkIc0QUg/0IZhCw92lPHfcNGceBSX/ux2DSxoVjFolxAGi/xku4VG99bd8fs=
  - secure: OeiYkD1us8mHMBuEQm1HKAvLlTwkJFEtpR/P4pwrz3DZ1M6E/QbTizEgF3VbSap/7jaBprj4T2VoitPox0SostmDezvRGGF0kAoCIbukzUF6vRfa7ugUadwcn9b6oMNhWSACp97yDIO5rZE2J6KoHAPV/FQ6D3dsYDmteHVc2LoLmEsJ1FmHS2TT9UMpG5t/WF30sN5wnLMGEg9thHLAWeA2XZMxVuGd23HquIA5F62VbTDINPZvn5NBn4EKNPoyqwDfnxTw3VYUrkOpwQj8SuSeMl/JWdCmf2TM8oPxAeqqQwoclEoMSFAm4zscoYmvjNVeBJcyVN2svHq48OmlEWTVpRUxkAG0tLU9/xJnMhanTX1ojKFmybAHUm5x93iIrbV2d/9bgNKOt1/SY6s2uCq6l+fTDlwEayqj+e9FXdGFs6jf8aVs0Y8ImP2g/k8TSxCPHo8OkC1/HX1eG5yg8V86kwBKbastKUJJbe28rwU9WzQ1NHpSkyBSYx3h0hDzZFMNjWV7fE9B9LNmFE6YPpP7iv/PCIPgtt17PrulIUXm7IWMylAODM3689ffSLm9BgU/zsUaz/kUQPWXl0kwXbIXD4ylc2CJiKSqWqDtQ4ygCt9p6fenrI4EBsRM5h7m7X8bxwASyJQN6eZpqUOC1s76s4aa6PWKYwlTtUO88xI=
deploy:
- provider: script
  skip_cleanup: true
  script: lein release :patch
  on:
    branch: master
