version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Make bb available globally
          command: sudo ln -fs `pwd`/bin/bb /usr/local/bin/bb
      - run:
          name: Generate config
          command: ./bin/run_library_tests.clj circle-continuation-config.yml
      - continuation/continue:
          configuration_path: circle-continuation-config.yml

workflows:
  setup:
    jobs:
      - setup
