version: 2.1
jobs:

  test:
    working_directory: ~/ci
    docker:
      # Primary container image where all steps run.
      - image: district0x/cljs-dev:latest
    steps:
      - checkout
      
      # Install Clojure Dependencies from Maven (cached)
      #- restore_cache:
      #    name: Restore m2 package cache
      #    keys:
      #      - maven-dependencies-{{ checksum "project.clj" }}
      #      # fallback to using the latest cache if no exact match is found
      #      - maven-dependencies-
      - run: lein deps
      #- save_cache:
      #    name: Save m2 package cache
      #    paths:
      #      - ~/.m2
      #    key: maven-dependencies-{{ checksum "project.clj" }}

      # Install NodeJS Dependencies from NPM (cached)
      #- restore_cache:
      #    name: Restore npm package cache
      #    keys:
      #      - npm-packages-{{ checksum "package-lock.json" }}
      - run: lein npm install
      #- save_cache:
      #    name: Save npm package cache
      #    key: npm-packages-{{ checksum "package-lock.json" }}
      #    paths:
      #      - ./node_modules/

      # Begin
      - run: make test

  deploy:
   machine: true
   steps:
     - checkout
     - run:
         name: Deploy to clojars
         command: lein release :patch

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
