sudo: required
dist: trusty
language: clojure
script: lein doo node "tests" once
addons:
  chrome: stable
before_script:
  - "echo 'Installing Ganache'"
  - npm install -g ganache-cli
  - "echo 'Running Ganache'"
  - ganache-cli -p 8549 > /dev/null &
