dist: bionic
language: clojure
node_js:
- '11'
script: lein doo node "nodejs-tests" once
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
before_install:
- nvm install 11.14.0
- nvm use 11.14.0
- npm install -g truffle@4.1.14
- npm install -g ganache-cli@6.1.8
before_script:
- ganache-cli -d -m district0x -p 8549 -l 8000000 > /dev/null &
- truffle migrate --network ganache --reset
env:
  global:
  - secure: qWy/Z6+Ig0HwaGUm8mTwDvZk+AaHP0wmTP02wZ/RTHJHiGakiLM2gF5cjUEuttuYlKJ+uyddX9UL+012ggS5p5bLz80YLPhA+EQlXQHDaQyRVML6fndZr4e+7T0Xl8MNjewoaS9U2Q4E1XjJQE5MCNLOfOl1MgyH3Kq7ifVN5oX3MiyzgcyrTuinjZRiul20rMmVZT1XB50NR5S5AUklFixk9xcCCiRaGyMO6/QTt6fXdnMPMfBYHnM+ExgiLu0rI4+t9DvSe+axH0rwxjepk739NNvnAferheDd/QiEv7ZOSw24Z08LTPgBT1Iu1xd4iK+bYVYWk5T1yyIcKOZEIhdcC3GE/P3yZd1oH4OUQP1iQt1Hr23sa8XZL9dJ06aG2MWAAmQEt18WZhnPxE+HnO1BV+uloaLSgT4zeGDfiICPOQy8vsYSsVkqqQEgFaUIHMksec7GUhuBIkLO0y2TsqcbVvSLtvzL3jn0SCooLfIgxze8yMhJ5k3POUfpOkR0gMK3a/wBfvOKBYzLEgKGHN1LZL3kAjiz2kewVcZ0OWzjaOmU+lGxqY6G4WEw+moxitWxWQ8fRfIajmnz9B9SfRfSb0l7Zo6kRN3yKYAVlgOgK5kX5ARnn7YAvhQTWaZ3R+hy5LctU12gJa2JJEp+VaJdInO4S/sQTjsOuFZ4HPU=
  - secure: l5oQTlm/pThhjpgFC8zNMC22J88nxcGs6x1YmJHSsGL5UzWDAdEn3+JFCPWpRU4oM+rcryhRZRIp+xdxpidlnfo9AflMqvfKSnDXVUCDdoMj2Fp23DB3s3zKHxVb0JkNIwj1WLhvcLs78FOam94llGg2H/Wd9Oa0QCt1WqPa2xfJv2W8IqUtkPyw1LostyBIPgHj0gdMel9C6MsAXvWZ3wSuS1GN/3pdHTY/n7vua8BHXHpE03rgP5aY9d3kmflW5Wq6LL7FfTqwKlq5t/QhArDX8AjvQm+gLUxukwhTesHNSQ8kNrdvb9FjL8m9a8Cw5YVEjgUTg3+bQK39yOA+b8ugm5ZXaWCckOg8YaFuzFm0IjbXF/srlhzgiWpFm+SvjWoNPZjnYotEQ8JeTjKvBx0h3Mnv1WOIFHO9pAYdi54I7tXvyzNP12mdBg+B0CAs1PMeLeebrRPxVg09tXHAQquMJci+J5UpwN2Dqr8wU/r04HzDD7+SnREuH0jBNnQk30Dc8BwAo+zxcn4eETPsd/tGv2kirL98aoqjHiojyUxAgMeZBBKgfkTvS3Z5GtYCzRSlgfJbHMjCu0A8yCw6j2Oi2dOHNSBLWJB5j18Ga3BN0dDYyQ26xb8DGzlpn6Rn10GMBeyqF1Ke12vYMxu9Rw+hNy7enC87LMWC08ApMmw=
deploy:
- provider: script
  skip_cleanup: true
  script: lein release :patch
  on:
    branch: master
