version: 2.1
jobs:

  test:
    working_directory: ~/ci
    docker:
      # Primary container image where all steps run.
      - image: district0x/cljs-dev
      # Secondary container image on common network.
      - image: trufflesuite/ganache-cli:latest
        command: [-d, -m district0x, -p 8545, -l 8000000]
    steps:
      - checkout
      - run: lein npm install
      - run: truffle migrate --network ganache --reset
      - run: lein doo node "nodejs-tests" once

  deploy:
   machine: true
   steps:
     - checkout
     - run:
         name: Deploy to clojars
         command: lein release :patch

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
