version: 2.1
jobs:

  test:
    working_directory: ~/ci
    docker:
      - image: district0x/cljs-dev
    steps:
      - checkout
      - run: ganache-cli -d -m district0x -h 0.0.0.0 -p 8549 -l 8000000 > /dev/null &
      - run: apt-get install net-tools lsof
      - run: netstat -atu
      - run: truffle migrate --network ganache --reset
      - run: lein npm install
      - run: lein doo node "nodejs-tests" once

  deploy:
   machine: true
   steps:
     - checkout
     - run:
         name: Deploy to clojars
         command: lein release :patch

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
