language: clojure
script: lein doo node "tests" once
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
  email: false
before_install:
- sudo add-apt-repository --yes ppa:ethereum/ethereum
- sudo apt-get -qq update
before_script:
- echo 'Installing Solc'
- sudo wget --no-check-certificate -P /bin https://github.com/ethereum/solidity/releases/download/v0.4.24/solc-static-linux
- sudo chmod a+x /bin/solc-static-linux
- sudo ln -s /bin/solc-static-linux /usr/bin/solc
- echo 'Compiling contracts'
- lein solc once
- echo 'Installing Ganache'
- npm install -g ganache-cli
- echo 'Running Ganache'
- ganache-cli -p 8549 -l 8000000 -d -m district0x > /dev/null &
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote rm origin
- git remote add origin https://${GH_TOKEN}@github.com/district0x/district-server-web3-events.git > /dev/null 2>&1
env:
  global:
  - secure: jo/ugK393TRkHigPmVN7sSJib986hil1oAn6WG8Sc/pKRXZtOo0Koi3sutl9+74LT75PfZKSAUl4ye5/6ONaPaIOOX3IP/G3J3acj7nUr44/1DeQDbAztnta4QikEckvCMKiXkEH35NL6ToTYzDWpPPr5nmoGCaKEm2zxfxRTI6ap9dDS5sEB5FFBYGXuEjp6Ch9rf0ZHn97k+XWAzkKW34oN9UOiMxj1uk30kmYZdQ5vG4jOJ2vhZctvPfPjWSO3sJTT47MAchLBrx0/4ZrS9EInSY1X7X+PKc8x1Yfee0Q7VM1EGPYg6WTtNgelXjueaphwlTe9a43cEIdgQ0n8Z97wWvgvNYplrjsKjkcmORgybp+HQMpH0FStvC7wzlQcPtswl+FFOiAvF2/LNkLuWVKuIaBnRQ9+opW0EW6hwppbOJyC2rSNMfgDxnUlF4ePO6gq3qyEB800FNSZiruFRAmy+2qsDZvPbjBzTRfrLND5fULiXDUas7q2d/y49Ki2d4qtSzSBe36uTbphPmjN9+d6vemP8cvDCZA4RyibSwdRVTGO6fEeQAXYWXxlx0T+55jkbJc60fYrKeFEkVgdbCanGicdSDoOBrn1rxRFTgg75QwVMA+SSCw6/UynUdY69Oilrkqqk1XJ6oHNTiTOXlsBdwEPyABurcemSOXvO0=
  - secure: SUYoS5fKl8UkuMmD3E9nPiu6Cf9Qj65kN8sTdwcPI2ZNe9v1A6c6BLKhsT/pkZYYbfbCBbu8pIXIerw+OXNfKlFyu4tecT2hVLwlkVqhFvPfMaQQOPjReE9vil2WOskHa9KuBJE2L+eeOVZG0xagTbRxO2XG7uPF2TZadE5J0LSQFyf0tb45ULtLLtr0Y1sxiwPoJhoUV6644Kz12Jp9qcPRZA0E5Aj8hQU4NzhbORiCUzAPKj6UfT7fErnCcrVpUQthhitT5oEKmipbn5mpW26JPZffHkpTENWP4H/dHsR2vkAqQE56h3XVvSJzYFNIccWY1rr/x27qpjpDaIExXADkt7CC9ZfR9HHYlK+J51LLaeem8Ks1aubLHqRYbtcD0ZOxHzzODH/SmL5PAv3DUeeCVyREr9wh4sQEycG9XgJ3bbWvB7UV9UfZG1ka+ToYh1ThUTmRSxGo+ppeYSgsoEN2JTO4zVYGj7FluTONJ7mi/jbUGDLtdf+qLzXqqCAazwM2NHlb5aNqFQs+gbBdjgL8glfEnQgjlKVnwh2Q0HlEXG4ix4YGjw8LeH+yAVhcBYaxZyNKCaNIiW3hdkGXe7bCR7QTEUjV2OuJkdPIXBHhNCHrwPIZ/E4F3+wk96awvMowTE+tq/VWE85N9FEwFwIPrz7Kolcve1kd/TNcidE=
deploy:
- provider: script
  skip_cleanup: true
  script: lein release :patch
  on:
    branch: master
