language: clojure
script: lein doo node "tests" once
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
  email: false
before_install:
- sudo add-apt-repository --yes ppa:ethereum/ethereum
- sudo apt-get -qq update
before_script:
- echo 'Installing Solc'
- sudo wget --no-check-certificate -P /bin https://github.com/ethereum/solidity/releases/download/v0.4.24/solc-static-linux
- sudo chmod a+x /bin/solc-static-linux
- sudo ln -s /bin/solc-static-linux /usr/bin/solc
- echo 'Compiling contracts'
- lein solc once
- echo 'Installing Ganache'
- npm install -g ganache-cli
- echo 'Running Ganache'
- ganache-cli -p 8549 -l 8000000 -d -m district0x > /dev/null &
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote rm origin
- git remote add origin https://${GH_TOKEN}@github.com/district0x/district-server-web3-events.git
  > /dev/null 2>&1
deploy:
- provider: script
  skip_cleanup: true
  script: lein release :patch
  on:
    branch: master
env:
  global:
  - secure: qoTLCQxtUPRmWUBK+K+RwoKtJd6I7DF07Xj5rmTSpilhByMFLXC/2A1InxPCqY8+mBU24JARi8e+Q0S342g5WFSBSXJxrNahPgnmIzcWmqosUc2M2Jxv4iAqvtRI/fq4tZkzW8cxe2hoXmQVJxJq9QdDhHWUPvUT/pDXlw8sYYEwxHp1rUwP21W7PSiwww+79MvxpEBQxbLozGmruE7d+BhmkpTovPX/XMxGCyszalnZN9HU/Hg/9mHUUUNnh5HX1fUMsPz6e1uFTS2kfanKCuFHtADFxL38d21n9NLApwy5XfXpoRMJN9U3mwT3dHJ3GoPNACupSksDM5fB8mPRrtmH3GWhE5CmaxZhdWT+CT94AqM9wv4vxzvocalU2rlHdyHT8ug7Yo5vXVP14josvDtpY78gdspf1JFDQlrr4nGY8mlGCcXDDypYTk4ZwL6gsqtMiAfoqlKWjzq20chbZ1H1u7Lp9Opb0fxEvtSl9sqydrFCA6m7p71A+P2hSx+c9+Dtw28Bco+62zId0fh344OBMfl1+Ww5Msakitn9YJv/hJ12APCYgniSogqRSEgSYKpQUVP2KNdWHeibqgVelHSuqxO6E8rdvKAKU90nVWmrcS6ngzebqF1yjcAQMuP9X9cTesIpw9LOnOpPDbtSunAdreU/8wfH6EXt+KLlawA=
  - secure: NH4xMPMuSN2SoyNn1GiWPNdvMa/TKStq+/Xe2ndtKNfxVPLJ+BKtoh7HXcdRkv7wAL3Hpqixns4MohMedzVDPV3eDFaAav+F/50uYviNwh5pn5FinYaAhCPuDow3OeYI4+iaNAo6JeNuytci9jU2rLMFiRKQYeUT3/m+gsgdlxcwqr85drUc9KS+lVLOsFiFUmTd4G4GGHQZ/SaTP5r/+CkZ1spSZVtuE5gWIXGuBkHU7k1v8uc7ugvkKbnZrClVe9nxFfche0tSrd9iRbK/Bwe5Jv4596A2AYum3M6uGU6BpDQcGryG0I6Y4KQ7+5hzg8v3zphrxh2XfNypdXaJ17R9TYjwLTf21fP0SZ03OHJCaZHVXpsRyMI3shtymUtnQ1jEsHbe5JDYtcTm6/yMGc8GXu97dnA9r+wLaAdx7itkawLsuvwarS2wZXpyLmP5Sj7DpFbnE7QN+eG0z2kfCCUFTSRIT7dsQfqMo0F7/p4qRsuEHNs0hOLaNvbzHeSTnnU/khcB6meTNSv5XYQ1ivMSA3MlzVMz3JAuKOo05/LFcrYJWMpKi3K5vTVrriY3AsAzJ1tc9fw7/GUOqdaBo4jpDGTFRV4rZGI3QwK+XtuXVE89JwmRxvaoQbhvA5L0cTKO3obsKx+eqr5jzUvxjUEds8VfImyNcYLTLGejZ8s=
